### PR TITLE
Error for maximum context length

### PR DESCRIPTION
**Pull request by tomekz**
show error view if max tokens count for the current model is exceeded

### CODE REVIEW

**Comment by savannahostrowski** [comment]
Apologies for not reviewing this very promptly - it's on my list! Thanks for submitting the PR.

**Comment by tomekz** [comment]
you're welcome @savannahostrowski . I would appreciate if you could review it this month still so it could count towards my hacktoberfest contribution

**Comment by savannahostrowski** [comment]
LGTM! Thank you!

**Comment by savannahostrowski** [comment]
@all-contributors please add @tomekz for code

**Pull request merged**
